In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (2.17.0)
Requirement already satisfied: tensorflow-intel==2.17.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow) (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (4.25.4)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (70.2.0)
Requirement already satisfied: six>=1.12.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.65.4)
Requirement already satisfied: tensorboard<2.18,>=2.17 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (3.4.1)
Requirement already satisfied: numpy<2.0.0,>=1.26.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorflow-intel==2.17.0->tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.17.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.17.0->tensorflow) (2024.7.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow-intel==2.17.0->tensorflow) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\deepa\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow-intel==2.17.0->tensorflow) (0.1.2)

In [102]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
import matplotlib.pyplot as plt

In [103]:
df=pd.read_csv("cardekho_data.csv")

In [104]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [105]:
df['Year']=2024-df['Year']

In [106]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,11,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,7,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,13,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,10,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,8,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,9,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,15,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,7,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,8,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [107]:
df['Year']=2024-df['Year']

In [111]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,11,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,7,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,13,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,10,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,8,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,9,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,15,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,7,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,8,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [109]:
from datetime import datetime
df['Year']=datetime.now().year-df['Year']

In [114]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,11,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,7,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,13,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,10,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,8,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,9,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,15,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,7,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,8,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [115]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [79]:
df['Car_Name']=le.fit_transform(df['Car_Name'])

In [80]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,90,10,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,93,11,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,68,7,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,96,13,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,92,10,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,69,8,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,66,9,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,69,15,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,69,7,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,66,8,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    int32
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int32(1), int64(3), object(3)
memory usage: 20.1+ KB

In [116]:
col=df.select_dtypes(include=['object']).columns

In [117]:
for i in col:
    df[i]=le.fit_transform(df[i])

In [118]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,90,10,3.35,5.59,27000,2,0,1,0
1,93,11,4.75,9.54,43000,1,0,1,0
2,68,7,7.25,9.85,6900,2,0,1,0
3,96,13,2.85,4.15,5200,2,0,1,0
4,92,10,4.60,6.87,42450,1,0,1,0
...,...,...,...,...,...,...,...,...,...
296,69,8,9.50,11.60,33988,1,0,1,0
297,66,9,4.00,5.90,60000,2,0,1,0
298,69,15,3.35,11.00,87934,2,0,1,0
299,69,7,11.50,12.50,9000,1,0,1,0
300,66,8,5.30,5.90,5464,2,0,1,0

In [119]:
df.info

<bound method DataFrame.info of      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0          90    10           3.35           5.59       27000          2
1          93    11           4.75           9.54       43000          1
2          68     7           7.25           9.85        6900          2
3          96    13           2.85           4.15        5200          2
4          92    10           4.60           6.87       42450          1
..        ...   ...            ...            ...         ...        ...
296        69     8           9.50          11.60       33988          1
297        66     9           4.00           5.90       60000          2
298        69    15           3.35          11.00       87934          2
299        69     7          11.50          12.50        9000          1
300        66     8           5.30           5.90        5464          2

     Seller_Type  Transmission  Owner
0              0             1      0
1              0             1      0
2              0             1      0
3              0             1      0
4              0             1      0
..           ...           ...    ...
296            0             1      0
297            0             1      0
298            0             1      0
299            0             1      0
300            0             1      0

[301 rows x 9 columns]>

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    int32
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    int32
 6   Seller_Type    301 non-null    int32
 7   Transmission   301 non-null    int32
 8   Owner          301 non-null    int64
dtypes: float64(2), int32(4), int64(3)
memory usage: 16.6 KB

In [120]:
x=df.drop('Selling_Price',axis=1)

In [126]:
y=df.Selling_Price

In [127]:
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [128]:
from sklearn.preprocessing import StandardScaler

In [129]:
sc=StandardScaler()

In [130]:
x=sc.fit_transform(x)

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [133]:
from tensorflow.keras.models import Sequential

In [134]:
from tensorflow.keras.layers import Dense,Flatten

In [135]:
from tensorflow.keras.optimizers import Adam

In [136]:
model =Sequential()

model.add(Dense(32,input_dim=x_train.shape[1],activation="relu"))
model.add(Dense(64,activation="relu"))

model.add(Flatten())
model.add(Dense(1))

C:\Users\deepa\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [137]:
optimizer =Adam(learning_rate=0.001)

In [138]:
model.compile(optimizer=optimizer,loss="mean_squared_error",metrics=['accuracy'])

In [139]:
model.fit(x_train,y_train,epochs=150)

Epoch 1/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0000e+00 - loss: 63.2330
Epoch 2/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 54.3782
Epoch 3/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 53.2203
Epoch 4/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 40.7999
Epoch 5/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 32.9828
Epoch 6/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0027 - loss: 32.3005
Epoch 7/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 34.3825
Epoch 8/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 33.9061
Epoch 9/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 28.8998
Epoch 10/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 23.5714
Epoch 11/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 24.7720
Epoch 12/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 14.8111
Epoch 13/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 9.8143
Epoch 14/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 10.9125
Epoch 15/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 9.7401
Epoch 16/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 7.4003
Epoch 17/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 5.8706
Epoch 18/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 6.4300
Epoch 19/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 5.0831
Epoch 20/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2710
Epoch 21/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 4.1078
Epoch 22/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 3.2528
Epoch 23/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 2.5654
Epoch 24/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 1.8724
Epoch 25/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 1.8707
Epoch 26/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 1.7485
Epoch 27/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 1.7730
Epoch 28/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0000e+00 - loss: 1.5360
Epoch 29/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 1.5474
Epoch 30/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.9095
Epoch 31/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 1.2704
Epoch 32/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 1.0769
Epoch 33/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 1.1841
Epoch 34/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 1.1819
Epoch 35/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 1.2170
Epoch 36/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.9459
Epoch 37/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 1.2390
Epoch 38/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.9911
Epoch 39/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.8585
Epoch 40/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.8799
Epoch 41/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6952
Epoch 42/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.8702
Epoch 43/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.7807
Epoch 44/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.7727
Epoch 45/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.8555
Epoch 46/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.7244
Epoch 47/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0000e+00 - loss: 0.6875
Epoch 48/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.7126
Epoch 49/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6074
Epoch 50/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6315
Epoch 51/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.9125
Epoch 52/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.5890
Epoch 53/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.5298
Epoch 54/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.5268
Epoch 55/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.7396
Epoch 56/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6808
Epoch 57/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6206
Epoch 58/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 0.5159
Epoch 59/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.5317
Epoch 60/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 0.5832
Epoch 61/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.5708
Epoch 62/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0036 - loss: 0.5308
Epoch 63/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.5166
Epoch 64/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 0.5477
Epoch 65/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 0.6510
Epoch 66/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.4648
Epoch 67/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.7234
Epoch 68/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.5763
Epoch 69/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0014 - loss: 0.4947
Epoch 70/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.5507
Epoch 71/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0047 - loss: 0.6076
Epoch 72/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.5279
Epoch 73/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.5927
Epoch 74/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 0.5267
Epoch 75/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 0.5837
Epoch 76/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0065 - loss: 0.4943
Epoch 77/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.4849
Epoch 78/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0065 - loss: 0.4260
Epoch 79/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0047 - loss: 0.4510
Epoch 80/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 9.2593e-04 - loss: 0.4698
Epoch 81/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 0.5304
Epoch 82/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0036 - loss: 0.4416
Epoch 83/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 0.4665
Epoch 84/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0020 - loss: 0.5630
Epoch 85/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.4688
Epoch 86/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 9.2593e-04 - loss: 0.5019
Epoch 87/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0014 - loss: 0.4520
Epoch 88/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0065 - loss: 0.4958
Epoch 89/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0047 - loss: 0.4609
Epoch 90/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.5165
Epoch 91/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 0.5023
Epoch 92/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0027 - loss: 0.4668
Epoch 93/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0065 - loss: 0.4395
Epoch 94/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0020 - loss: 0.4954
Epoch 95/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0036 - loss: 0.6398
Epoch 96/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 0.3965
Epoch 97/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0047 - loss: 0.4510
Epoch 98/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0036 - loss: 0.5913
Epoch 99/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0065 - loss: 0.3612
Epoch 100/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.4165
Epoch 101/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0036 - loss: 0.5154
Epoch 102/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.4723
Epoch 103/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 9.2593e-04 - loss: 0.4962
Epoch 104/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 0.3748
Epoch 105/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0036 - loss: 0.5227
Epoch 106/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.4076
Epoch 107/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0027 - loss: 0.4211
Epoch 108/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0027 - loss: 0.5652
Epoch 109/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.5721
Epoch 110/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0099 - loss: 0.4997
Epoch 111/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0065 - loss: 0.5369
Epoch 112/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0065 - loss: 0.3596
Epoch 113/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0014 - loss: 0.5638
Epoch 114/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0027 - loss: 0.4083
Epoch 115/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 9.2593e-04 - loss: 0.4228
Epoch 116/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.4517
Epoch 117/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0036 - loss: 0.4225
Epoch 118/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.3658
Epoch 119/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0020 - loss: 0.4644
Epoch 120/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0047 - loss: 0.3704
Epoch 121/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 9.2593e-04 - loss: 0.3749
Epoch 122/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0099 - loss: 0.3581
Epoch 123/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0014 - loss: 0.4990
Epoch 124/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0027 - loss: 0.5062
Epoch 125/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0014 - loss: 0.4116
Epoch 126/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0065 - loss: 0.4083
Epoch 127/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0047 - loss: 0.4070
Epoch 128/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0020 - loss: 0.4075
Epoch 129/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0047 - loss: 0.5233
Epoch 130/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0014 - loss: 0.4189
Epoch 131/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0047 - loss: 0.4554
Epoch 132/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0020 - loss: 0.3760
Epoch 133/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 9.2593e-04 - loss: 0.3932
Epoch 134/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0027 - loss: 0.3674
Epoch 135/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0036 - loss: 0.4454
Epoch 136/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0099 - loss: 0.3982
Epoch 137/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 9.2593e-04 - loss: 0.3963
Epoch 138/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0099 - loss: 0.3219
Epoch 139/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0027 - loss: 0.5199
Epoch 140/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0036 - loss: 0.4193
Epoch 141/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0065 - loss: 0.4767
Epoch 142/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0065 - loss: 0.4441
Epoch 143/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0020 - loss: 0.4769
Epoch 144/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 9.2593e-04 - loss: 0.3912
Epoch 145/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 9.2593e-04 - loss: 0.3285
Epoch 146/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0099 - loss: 0.4311
Epoch 147/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0065 - loss: 0.4196
Epoch 148/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0014 - loss: 0.3596
Epoch 149/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0065 - loss: 0.3495
Epoch 150/150
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0020 - loss: 0.4363

In [140]:
y_pred=model.predict(x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

In [141]:
y_pred

array([[-1.15338951e-01],
       [ 1.02452545e+01],
       [ 4.85801888e+00],
       [-2.05526203e-02],
       [ 8.15442657e+00],
       [ 6.64359665e+00],
       [ 7.74621367e-01],
       [ 7.33074903e-01],
       [ 4.91034776e-01],
       [ 6.41778898e+00],
       [ 1.17532072e+01],
       [ 7.52111554e-01],
       [ 8.39007568e+00],
       [ 5.23476005e-01],
       [ 5.64468384e+00],
       [ 3.14612055e+00],
       [ 7.99327254e-01],
       [ 1.40859518e+01],
       [ 8.85732412e-01],
       [ 1.59837914e+00],
       [ 6.56198621e-01],
       [ 8.83366585e+00],
       [ 4.76253510e+00],
       [ 2.89413238e+00],
       [ 4.62316513e-01],
       [ 3.68428063e+00],
       [ 4.52219772e+00],
       [ 2.56450152e+00],
       [ 1.27146482e+00],
       [ 9.75571275e-01],
       [ 6.05993390e-01],
       [ 9.33297348e+00],
       [ 6.20097876e-01],
       [ 2.26902962e+00],
       [ 9.36117744e+00],
       [ 4.58962727e+00],
       [ 5.31220531e+00],
       [ 5.19954109e+00],
       [ 3.20563293e+00],
       [ 5.62678051e+00],
       [ 3.57461762e+00],
       [ 1.31657112e+00],
       [ 4.57321739e+00],
       [ 5.96977592e-01],
       [ 6.71908140e+00],
       [ 5.90134859e-01],
       [ 7.33924294e+00],
       [ 6.02829027e+00],
       [ 2.97705913e+00],
       [ 2.93779659e+00],
       [ 6.05868816e+00],
       [ 1.39043891e+00],
       [ 2.34577522e+01],
       [ 2.36206474e+01],
       [ 7.35464668e+00],
       [ 1.01813221e+01],
       [ 4.04302216e+00],
       [ 1.02865543e+01],
       [ 2.20404053e+00],
       [ 8.42045593e+00],
       [ 4.62674618e-01]], dtype=float32)

In [143]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [144]:
mse=mean_squared_error(y_pred,y_test)

In [145]:
mse

0.6083650810951196

In [146]:
mae=mean_absolute_error(y_pred,y_test)

In [147]:
mae

0.5298109941306662

In [149]:
r2_score(y_test,y_pred)

0.973590204296346

In [151]:
y_pred_train=model.predict(x_train)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [152]:
r2_score(y_pred_train,y_train)

0.9854984612648898